EMAIL_SENDER = "EMAIL_SENDER"
EMAIL_PASSWORD = "APP_PASSWORD_GENERATE_FROM_GOOGLE"
EMAIL_RECEIVER = "EMAIL_RECIEVER"

THREAT_LABELS = ["cyberbullying", "hate speech", "scam", "terrorism", "violence"]
THREAT_THRESHOLD = 0.7
